### PR TITLE
double image loading

### PR DESCRIPTION
**Pull request by skibz**
getListings() was downloading and generating the same images twice.
the function that checked whether an image existed has now been altered to return just the initially created image element instead.

### CODE REVIEW

**Comment by Rock48** [comment]
Looks pretty good; Add yourself as a contributor in about.html

**Comment by skibz** [comment]
cool :+1:

**Comment by CyrisXD** [comment]
Brilliant @skibz

**Comment by CyrisXD** [comment]
@skibz could you work on this? After merge I noticed a few bugs. CSS animations aren't working, search isn't working etc.. I believe it has something to do with the "missingName" divs overlapping the content or something. 

2015-02-23 13_52_08-steam roller - steam quick launch

**Comment by skibz** [comment]
cool - will investigate this

**Pull request merged**
