### PR TITLE
Build system (Gulp)

### PR DESCRIPTION
**Pull request by odensc**
Adds building using node-webkit-builder and Gulp.

### CODE REVIEW

**Comment by CyrisXD** [comment]
Thanks Oden. Where did you push this from? I'm having a look at your fork to see how the file structuring has been set etc.. as I'm a little hesitant to add gulp to this project. I don't know gulp too well yet and would like to keep this as simple as possible.

**Comment by odensc** [comment]
@CyrisXD 

> Where did you push this from?

What do you mean by that?

> I'm having a look at your fork to see how the file structuring has been set etc.. as I'm a little hesitant to add gulp to this project. I don't know gulp too well yet and would like to keep this as simple as possible.

A quick explanation:
"gulp/": All the gulp task files.
"builds/": All of the SteamRoller builds will be put here after gulp is run.
"dist/": The copied / compiled files from src/
"src/": The html files, images, js, css, etc.
"src/public": All of these files get put into the root of the dist/

**Comment by thesbros** [comment]
I'm going to go ahead and close this until we discuss at #22.

**Comment by odensc** [comment]
I'm going to go ahead and put this on hold until we discuss at #22.

**Comment by TheDrDocter** [comment]
Seems like a good idea considering the mess of folders you get when normally running the program

**Comment by CyrisXD** [comment]
@TheDrDocter Could you elaborate on the that? The only folder I've seen it create it the locales folder in the root directory. Any others are general storage folders in AppData windows system.

**Comment by TheDrDocter** [comment]
@CyrisXD not sure I read this right or not, but this whole gulp thing and what not will organize all the files to one folder rather that all these "nw####_####" folders in my temp folder

**Pull request closed without merging**
