### PR TITLE
Update SteamRoller.html

### PR DESCRIPTION
**Pull request by TheDrDocter**
Adding the settings button back for easy switching between accounts. Although the "Save" button looks pretty bad I'm sure we can fix this with some handy-dandy CSS work in the stylesheet.

### CODE REVIEW

**Comment by CyrisXD** [comment]
I've disabled the settings button for now as I'm not sure if that function works yet.

**Comment by odensc** [comment]
Have you tested this (changing usernames)? I'm assuming there was a reason for it to be commented out.

**Comment by TheDrDocter** [comment]
I have tested the button before and it seems to work. I looked at a friends accoutn, any game he had that I didn't sent me to the steam store.

**Comment by odensc** [comment]
@TheDrDocter Alright, I'll test it real quick and merge if it works.

**Comment by odensc** [comment]
@TheDrDocter It seemed to work. I'll merge this into a separate branch (`feature/change-username`) until the CSS looks better. a091eccde35a0244ca9d50f6805921f6505b7188

**Pull request merged**
