### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by skibz**
- fixed version number (npm refuses to work on my computer without a semver type version number)
- added the usual suspects for dev deps (assertion libraries, test runner, etc)
- made the packagejson private, cause, yknow :P
- this just needs my gitignore additions now...
- added scripts block (more to appear here)
- added contributors list

### CODE REVIEW

**Comment by skibz** [comment]
@CyrisXD  
https://github.com/CyrisXD/SteamRoller-Steam-Quick-Launcher/pull/15

i, too, am hesitant about adding gulp. this project only needs a few command line programs for package maintenance. a `build` task that would help with generating releases, a `dev` task to build and run the project locally and finally a `test` task to run a test suite. not much more is needed, by the looks of things.

**Comment by odensc** [comment]
@CyrisXD @skibz 
What else would you suggest? Make scripts like build.js, test.js, etc. and add them to the package.json scripts?

**Comment by skibz** [comment]
@thesbros if we used gulp, it would allow us to add the `gulp-node-webkit-builder` tool which frees us of worrying about the state of `node-webkit-builder` (it's pretty unhealthy right now - broken for os x)

but i do, personally, prefer just using npm scripts.

**Comment by odensc** [comment]
@skibz `node-webkit-builder` worked fine for me on OS X last night.

**Comment by skibz** [comment]
@thesbros i can't build for os x due to this: https://github.com/mllrsohn/node-webkit-builder/issues/188

**Comment by odensc** [comment]
@skibz Does that only affect CLI? I was using the API.

**Comment by skibz** [comment]
@thesbros it does seem to only affect command line.
i was using `nwbuild -r .` to build and run while developing.

wanted to make a npm script a la: `./node_modules/.bin/nwbuild -r .`

**Comment by CyrisXD** [comment]
@skibz @thesbros you guys are obviously far more experienced with the tools and automation process than I am. To test my builds I've just been dragging the source folder over nw.exe, then to build I just use the command line.

Windows: Making an executable file out of a .nw file.
`copy /b nw.exe+app.nw app.exe`

Linux: Making an executable file out of a .nw file.
`cat /usr/bin/nw app.nw > app && chmod +x app`

Max OSX: Making an executable file out of a .nw file.
`https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps#mac-os-x`

I'm still fairly new to Node-webkit and have been learning as I was building. Found [this](https://gentlenode.com/journal/node-webkit-1-complete-cheatsheet/26) very useful.

**Comment by skibz** [comment]
@CyrisXD there isn't anything wrong with your testing process. and those are, indeed, good resources for learning.

@thesbros the issue i linked yesterday has been resolved. so `node-webkit-builder` now properly works on os x again! :tada: 

now we just have to decide on gulp or plain npm.

**Comment by odensc** [comment]
@skibz I mentioned Build System on #22 so you can put any opinions you have there if you want.

**Pull request merged**
