### PR TITLE
Added automatic scrolling when mouse is at top and bottom

### PR DESCRIPTION
**Pull request by Rock48**
My scroll wheel stopped working a couple days ago, this is super useful to me and I feel generally just a nice feature to have.
Edit: the boxes appear to obscure the bottom and top items. A reduction in height to 80 or 90px should fix that and make them accessible again
Edit 2: 
image

### CODE REVIEW

**Comment by CyrisXD** [comment]
This is great! Love the idea. I think the overlaying div might still be a bit too big. Maybe half that size so if you're hovering near the end it will scroll? And we need to make sure it doesn't cover the search drop down box when that is opened. What you think?

**Comment by CyrisXD** [comment]
Don't forget to add yourself to the About.html under Contributors :) Then I'll happily merge.

**Comment by Rock48** [comment]
Done!

**Comment by CyrisXD** [comment]
Thanks the size is perfect now. However it still seems to be covering the search bar once opened. Did you want to figure out a fix before merge? 

Screenshot:
2015-02-15 16_25_19-steam roller - steam quick launch

**Comment by Rock48** [comment]
Hmm, yeah, lemme see if I can fix that one.

**Comment by Rock48** [comment]
Fixed

I also gained a point in css class name creativity for the wonderful name "downabit"

**Comment by CyrisXD** [comment]
Did you commit the change? Not seeing it this side.

**Comment by Rock48** [comment]
Oops forgot to sync. done now.

**Comment by CyrisXD** [comment]
Great stuff! Merged :+1:

**Pull request merged**
